import logging
import time

def main() -> str:
    logging.info(f"[say_hello.main] Called at {time.strftime('%Y-%m-%d %H:%M:%S')}")
    time.sleep(1)  # Wait for 1 second to simulate some work
    return (
        "Hello! This message was generated by an activity function (a function with type=activityTrigger in function.json) as part of an Azure Durable Functions orchestration. The return value of an activity function is typically used by orchestrator functions ((a function with type=orchestrationTrigger in function.json)"
    )
